package com.nxtopencube;

import java.lang.reflect.Array;
import java.util.Arrays;

/* loaded from: classes.dex */
class CsCubieCube {

    /**
     * 16 symmetries generated by S_F2, S_U4 and S_LR2
     */
    static CsCubieCube[] CubeSym = new CsCubieCube[16];

    /**
     * 18 move cubes
     */
    static CsCubieCube[] moveCube = new CsCubieCube[18];

    static long[] moveCubeSym = new long[18];
    static int[] firstMoveSym = new int[48];

    static int[] preMove = { -1, CsUtil.Rx1, CsUtil.Rx3, CsUtil.Fx1, CsUtil.Fx3, CsUtil.Lx1, CsUtil.Lx3, CsUtil.Bx1, CsUtil.Bx3};

    static int[] SymInv = new int[16];
    static int[][] SymMult = new int[16][16];
    static int[][] SymMove = new int[16][18];
    static int[][] SymMultInv = new int[16][16];
    static int[] Sym8Mult = new int[8 * 8];
    static int[] Sym8Move = new int[8 * 18];
    static int[] Sym8MultInv = new int[8 * 8];
    static int[][] SymMoveUD = new int[16][10];

    /**
     * ClassIndexToRepresentantArrays
     */
    static char[] FlipS2R = new char[336];
    static char[] TwistS2R = new char[324];
    static char[] EPermS2R = new char[2768];
    static int[] UDSliceFlipS2R = CsSearch.USE_FULL_PRUN ? new int[64430] : null;

    /**
     * Notice that Edge Perm Coordnate and Corner Perm Coordnate are the same symmetry structure.
     * So their ClassIndexToRepresentantArray are the same.
     * And when x is RawEdgePermCoordnate, y*16+k is SymEdgePermCoordnate, y*16+(k^e2c[k]) will
     * be the SymCornerPermCoordnate of the State whose RawCornerPermCoordnate is x.
     */
    static byte[] e2c = {0, 0, 0, 0, 1, 3, 1, 3, 1, 3, 1, 3, 0, 0, 0, 0};

    static char[] MtoEPerm = new char[40320];

    static int[] FlipSlice2UDSliceFlip = CsSearch.USE_FULL_PRUN ? new int[CsCoordCube.N_FLIP_SYM * CsCoordCube.N_SLICE] : null;

    /**
     * Raw-Coordnate to Sym-Coordnate, only for speeding up initializaion.
     */
    static char[] FlipR2S;// = new char[2048];
    static char[] TwistR2S;// = new char[2187];
    static char[] EPermR2S;// = new char[40320];
    static char[] FlipS2RF = CsSearch.USE_TWIST_FLIP_PRUN ? new char[336 * 8] : null;
    static char[] TwistS2RF = CsSearch.USE_FULL_PRUN ? new char[324 * 8] : null;

    /**
     *
     */
    static char[] SymStateTwist = new char[324];
    static char[] SymStateFlip = new char[336];
    static char[] SymStatePerm = new char[2768];
    static char[] SymStateUDSliceFlip = CsSearch.USE_FULL_PRUN ? new char[64430] : null;

    static CsCubieCube urf1 = new CsCubieCube(2531, 1373, 67026819, 1367);
    static CsCubieCube urf2 = new CsCubieCube(2089, 1906, 322752913, 2040);
    static byte[][] urfMove = new byte[][] {
            {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
            {6, 7, 8, 0, 1, 2, 3, 4, 5, 15, 16, 17, 9, 10, 11, 12, 13, 14},
            {3, 4, 5, 6, 7, 8, 0, 1, 2, 12, 13, 14, 15, 16, 17, 9, 10, 11},
            {2, 1, 0, 5, 4, 3, 8, 7, 6, 11, 10, 9, 14, 13, 12, 17, 16, 15},
            {8, 7, 6, 2, 1, 0, 5, 4, 3, 17, 16, 15, 11, 10, 9, 14, 13, 12},
            {5, 4, 3, 8, 7, 6, 2, 1, 0, 14, 13, 12, 17, 16, 15, 11, 10, 9}
    };

    byte[] cp = {0, 1, 2, 3, 4, 5, 6, 7};
    byte[] co = {0, 0, 0, 0, 0, 0, 0, 0};
    byte[] ep = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    byte[] eo = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    CsCubieCube temps = null;

    CsCubieCube() {
    }

    CsCubieCube(int cperm, int twist, int eperm, int flip) {
        this.setCPerm(cperm);
        this.setTwist(twist);
        CsUtil.setNPerm(ep, eperm, 12);
        this.setFlip(flip);
    }

    CsCubieCube(CsCubieCube c) {
        copy(c);
    }

    public boolean equalsCorn(CsCubieCube c) {
        for (int i = 0; i < 8; i++) {
            if (cp[i] != c.cp[i] || co[i] != c.co[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean equalsEdge(CsCubieCube c) {
        for (int i = 0; i < 12; i++) {
            if (ep[i] != c.ep[i] || eo[i] != c.eo[i]) {
                return false;
            }
        }
        return true;
    }

    void copy(CsCubieCube c) {
        for (int i = 0; i < 8; i++) {
            this.cp[i] = c.cp[i];
            this.co[i] = c.co[i];
        }
        for (int i = 0; i < 12; i++) {
            this.ep[i] = c.ep[i];
            this.eo[i] = c.eo[i];
        }
    }

    void invCubieCube() {
        if (temps == null) {
            temps = new CsCubieCube();
        }
        for (byte edge = 0; edge < 12; edge++)
            temps.ep[ep[edge]] = edge;
        for (byte edge = 0; edge < 12; edge++)
            temps.eo[edge] = eo[temps.ep[edge]];
        for (byte corn = 0; corn < 8; corn++)
            temps.cp[cp[corn]] = corn;
        for (byte corn = 0; corn < 8; corn++) {
            byte ori = co[temps.cp[corn]];
            temps.co[corn] = (byte) - ori;
            if (temps.co[corn] < 0)
                temps.co[corn] += 3;
        }
        copy(temps);
    }

    /**
     * prod = a * b, Corner Only.
     */
    static void CornMult(CsCubieCube a, CsCubieCube b, CsCubieCube prod) {
        for (int corn = 0; corn < 8; corn++) {
            prod.cp[corn] = a.cp[b.cp[corn]];
            byte oriA = a.co[b.cp[corn]];
            byte oriB = b.co[corn];
            byte ori = oriA;
            ori += (oriA < 3) ? oriB : 6 - oriB;
            ori %= 3;
            if ((oriA >= 3) ^ (oriB >= 3)) {
                ori += 3;
            }
            prod.co[corn] = ori;
        }
    }

    /**
     * prod = a * b, Edge Only.
     */
    static void EdgeMult(CsCubieCube a, CsCubieCube b, CsCubieCube prod) {
        for (int ed = 0; ed < 12; ed++) {
            prod.ep[ed] = a.ep[b.ep[ed]];
            prod.eo[ed] = (byte) (b.eo[ed] ^ a.eo[b.ep[ed]]);
        }
    }

    /**
     * b = S_idx^-1 * a * S_idx, Corner Only.
     */
    static void CornConjugate(CsCubieCube a, int idx, CsCubieCube b) {
        CsCubieCube sinv = CubeSym[SymInv[idx]];
        CsCubieCube s = CubeSym[idx];
        for (int corn = 0; corn < 8; corn++) {
            b.cp[corn] = sinv.cp[a.cp[s.cp[corn]]];
            byte oriA = sinv.co[a.cp[s.cp[corn]]];
            byte oriB = a.co[s.cp[corn]];
            b.co[corn] = (byte) ((oriA < 3) ? oriB : (3 - oriB) % 3);
        }
    }

    /**
     * b = S_idx^-1 * a * S_idx, Edge Only.
     */
    static void EdgeConjugate(CsCubieCube a, int idx, CsCubieCube b) {
        CsCubieCube sinv = CubeSym[SymInv[idx]];
        CsCubieCube s = CubeSym[idx];
        for (int ed = 0; ed < 12; ed++) {
            b.ep[ed] = sinv.ep[a.ep[s.ep[ed]]];
            b.eo[ed] = (byte) (s.eo[ed] ^ a.eo[s.ep[ed]] ^ sinv.eo[a.ep[s.ep[ed]]]);
        }
    }

    /**
     * this = S_urf^-1 * this * S_urf.
     */
    void URFConjugate() {
        if (temps == null) {
            temps = new CsCubieCube();
        }
        CornMult(urf2, this, temps);
        CornMult(temps, urf1, this);
        EdgeMult(urf2, this, temps);
        EdgeMult(temps, urf1, this);
    }

    // ********************************************* Get and set coordinates *********************************************
    // XSym : Symmetry Coordnate of X. MUST be called after initialization of ClassIndexToRepresentantArrays.

    // ++++++++++++++++++++ Phase 1 Coordnates ++++++++++++++++++++
    // Flip : Orientation of 12 Edges. Raw[0, 2048) Sym[0, 336 * 8)
    // Twist : Orientation of 8 Corners. Raw[0, 2187) Sym[0, 324 * 8)
    // UDSlice : Positions of the 4 UDSlice edges, the order is ignored. [0, 495)

    int getFlip() {
        int idx = 0;
        for (int i = 0; i < 11; i++) {
            idx = idx << 1 | eo[i];
        }
        return idx;
    }

    void setFlip(int idx) {
        int parity = 0;
        for (int i = 10; i >= 0; i--) {
            parity ^= eo[i] = (byte) (idx & 1);
            idx >>= 1;
        }
        eo[11] = (byte)parity;
    }

    int getFlipSym() {
        if (FlipR2S != null) {
            return FlipR2S[getFlip()];
        }
        if (temps == null) {
            temps = new CsCubieCube();
        }
        for (int k = 0; k < 16; k += 2) {
            EdgeConjugate(this, SymInv[k], temps);
            int idx = Arrays.binarySearch(FlipS2R, (char) temps.getFlip());
            if (idx >= 0) {
                return idx << 3 | k >> 1;
            }
        }
        assert false;
        return 0;
    }

    int getTwist() {
        int idx = 0;
        for (int i = 0; i < 7; i++) {
            idx += (idx << 1) + co[i];
        }
        return idx;
    }

    void setTwist(int idx) {
        int twst = 0;
        for (int i = 6; i >= 0; i--) {
            twst += co[i] = (byte) (idx % 3);
            idx /= 3;
        }
        co[7] = (byte) ((15 - twst) % 3);
    }

    int getTwistSym() {
        if (TwistR2S != null) {
            return TwistR2S[getTwist()];
        }
        if (temps == null) {
            temps = new CsCubieCube();
        }
        for (int k = 0; k < 16; k += 2) {
            CornConjugate(this, SymInv[k], temps);
            int idx = Arrays.binarySearch(TwistS2R, (char) temps.getTwist());
            if (idx >= 0) {
                return idx << 3 | k >> 1;
            }
        }
        assert false;
        return 0;
    }

    int getUDSlice() {
        return CsUtil.getComb(ep, 8);
    }

    void setUDSlice(int idx) {
        CsUtil.setComb(ep, idx, 8);
    }

    int getU4Comb() {
        return CsUtil.getComb(ep, 0);
    }

    int getD4Comb() {
        return CsUtil.getComb(ep, 4);
    }

    // ++++++++++++++++++++ Phase 2 Coordnates ++++++++++++++++++++
    // EPerm : Permutations of 8 UD Edges. Raw[0, 40320) Sym[0, 2187 * 16)
    // Cperm : Permutations of 8 Corners. Raw[0, 40320) Sym[0, 2187 * 16)
    // MPerm : Permutations of 4 UDSlice Edges. [0, 24)

    int getCPerm() {
        return CsUtil.get8Perm(cp);
    }

    void setCPerm(int idx) {
        CsUtil.set8Perm(cp, idx);
    }

    int getCPermSym() {
        if (EPermR2S != null) {
            int idx = EPermR2S[getCPerm()];
            return idx ^ e2c[idx & 0xf];
        }
        if (temps == null) {
            temps = new CsCubieCube();
        }
        for (int k = 0; k < 16; k++) {
            CornConjugate(this, SymInv[k], temps);
            int idx = Arrays.binarySearch(EPermS2R, (char) temps.getCPerm());
            if (idx >= 0) {
                return idx << 4 | k;
            }
        }
        assert false;
        return 0;
    }

    int getEPerm() {
        return CsUtil.get8Perm(ep);
    }

    void setEPerm(int idx) {
        CsUtil.set8Perm(ep, idx);
    }

    int getEPermSym() {
        if (EPermR2S != null) {
            return EPermR2S[getEPerm()];
        }
        if (temps == null) {
            temps = new CsCubieCube();
        }
        for (int k = 0; k < 16; k++) {
            EdgeConjugate(this, SymInv[k], temps);
            int idx = Arrays.binarySearch(EPermS2R, (char) temps.getEPerm());
            if (idx >= 0) {
                return idx << 4 | k;
            }
        }
        return 0;
    }

    int getMPerm() {
        return CsUtil.getComb(ep, 8) >> 9;
    }

    void setMPerm(int idx) {
        CsUtil.setComb(ep, idx << 9, 8);
    }

    int getCComb() {
        return 69 - (CsUtil.getComb(cp, 0) & 0x1ff);
    }

    void setCComb(int idx) {
        CsUtil.setComb(cp, 69 - idx, 0);
    }

    /**
     * Check a cubiecube for solvability. Return the error code.
     * 0: Cube is solvable
     * -2: Not all 12 edges exist exactly once
     * -3: Flip error: One edge has to be flipped
     * -4: Not all corners exist exactly once
     * -5: Twist error: One corner has to be twisted
     * -6: Parity error: Two corners or two edges have to be exchanged
     */
    int verify() {
        int sum = 0;
        int edgeMask = 0;
        for (int e = 0; e < 12; e++) {
            edgeMask |= 1 << ep[e];
            sum ^= eo[e];
        }
        if (edgeMask != 0xfff) {
            return -2;// missing edges
        }
        if (sum != 0) {
            return -3;
        }
        int cornMask = 0;
        sum = 0;
        for (int c = 0; c < 8; c++) {
            cornMask |= 1 << cp[c];
            sum += co[c];
        }
        if (cornMask != 0xff) {
            return -4;// missing corners
        }
        if (sum % 3 != 0) {
            return -5;// twisted corner
        }
        if ((CsUtil.getNParity(CsUtil.getNPerm(ep, 12), 12) ^ CsUtil.getNParity(getCPerm(), 8)) != 0) {
            return -6;// parity error
        }
        return 0;// cube ok
    }

    long selfSymmetry() {
        CsCubieCube c = new CsCubieCube(this);
        CsCubieCube d = new CsCubieCube();
        long sym = 0L;
        for (int i = 0; i < 48; i++) {
            CornConjugate(c, SymInv[i % 16], d);
            if (d.equalsCorn(this)) {
                EdgeConjugate(c, SymInv[i % 16], d);
                if (d.equalsEdge(this)) {
                    sym |= 1L << i;
                }
            }
            if (i % 16 == 15) {
                c.URFConjugate();
            }
        }
        c.invCubieCube();
        for (int i = 0; i < 48; i++) {
            CornConjugate(c, SymInv[i % 16], d);
            if (d.equalsCorn(this)) {
                EdgeConjugate(c, SymInv[i % 16], d);
                if (d.equalsEdge(this)) {
                    sym |= 1L << 48;
                    break;
                }
            }
            if (i % 16 == 15) {
                c.URFConjugate();
            }
        }
        return sym;
    }

    void setUDSliceFlip(int idx) {
        setFlip(idx & 0x7ff);
        setUDSlice(idx >> 11);
    }

    int getUDSliceFlip() {
        return (getUDSlice() & 0x1ff) << 11 | getFlip();
    }

    int getUDSliceFlipSym() {
        int flip = getFlipSym();
        int fsym = flip & 0x7;
        flip >>= 3;
        int udslice = getUDSlice() & 0x1ff;
        int udsliceflip = FlipSlice2UDSliceFlip[flip * 495 + CsCoordCube.UDSliceConj[udslice][fsym]];
        return udsliceflip & 0xfffffff0 | SymMult[udsliceflip & 0xf][fsym << 1];
    }

    // ********************************************* Initialization functions *********************************************

    static void initMove() {
        moveCube[0] = new CsCubieCube(15120, 0, 119750400, 0);
        moveCube[3] = new CsCubieCube(21021, 1494, 323403417, 0);
        moveCube[6] = new CsCubieCube(8064, 1236, 29441808, 550);
        moveCube[9] = new CsCubieCube(9, 0, 5880, 0);
        moveCube[12] = new CsCubieCube(1230, 412, 2949660, 0);
        moveCube[15] = new CsCubieCube(224, 137, 328552, 137);
        for (int a = 0; a < 18; a += 3) {
            for (int p = 0; p < 2; p++) {
                moveCube[a + p + 1] = new CsCubieCube();
                EdgeMult(moveCube[a + p], moveCube[a], moveCube[a + p + 1]);
                CornMult(moveCube[a + p], moveCube[a], moveCube[a + p + 1]);
            }
        }
    }

    static void initSym() {
        CsCubieCube c = new CsCubieCube();
        CsCubieCube d = new CsCubieCube();
        CsCubieCube t;

        CsCubieCube f2 = new CsCubieCube(28783, 0, 259268407, 0);
        CsCubieCube u4 = new CsCubieCube(15138, 0, 119765538, 7);
        CsCubieCube lr2 = new CsCubieCube(5167, 0, 83473207, 0);
        lr2.co = new byte[] { 3, 3, 3, 3, 3, 3, 3, 3 };

        for (int i = 0; i < 16; i++) {
            CubeSym[i] = new CsCubieCube(c);
            CornMult(c, u4, d);
            EdgeMult(c, u4, d);
            t = d;  d = c;  c = t;
            if (i % 4 == 3) {
                CornMult(c, lr2, d);
                EdgeMult(c, lr2, d);
                t = d;  d = c;  c = t;
            }
            if (i % 8 == 7) {
                CornMult(c, f2, d);
                EdgeMult(c, f2, d);
                t = d;  d = c;  c = t;
            }
        }
        for (int i = 0; i < 16; i++) {
            for (int j = 0; j < 16; j++) {
                CornMult(CubeSym[i], CubeSym[j], c);
                for (int k = 0; k < 16; k++) {
                    if (CubeSym[k].equalsCorn(c)) {
                        SymMult[i][j] = k;
                        if (k == 0) {
                            SymInv[i] = j;
                        }
                        break;
                    }
                }
            }
        }
        for (int j = 0; j < 18; j++) {
            for (int s = 0; s < 16; s++) {
                CornConjugate(moveCube[j], SymInv[s], c);
                for (int m = 0; m < 18; m++) {
                    if (c.equalsCorn(moveCube[m])) {
                        SymMove[s][j] = m;
                        break;
                    }
                }
            }
        }
        for (int s = 0; s < 16; s++) {
            for (int j = 0; j < 10; j++) {
                SymMoveUD[s][j] = CsUtil.std2ud[SymMove[s][CsUtil.ud2std[j]]];
            }
            for (int j = 0; j < 16; j++) {
                SymMultInv[j][s] = SymMult[j][SymInv[s]];
            }
        }
        for (int s = 0; s < 8; s++) {
            for (int j = 0; j < 8; j++) {
                Sym8Mult[s << 3 | j] = SymMult[j << 1][s << 1] >> 1;
                Sym8MultInv[j << 3 | s] = SymMult[j << 1][SymInv[s << 1]]>>1;
            }
            for (int j = 0; j < 18; j++) {
                Sym8Move[j << 3 | s] = SymMove[s << 1][j];
            }
        }
        for (int i = 0; i < 18; i++) {
            moveCubeSym[i] = moveCube[i].selfSymmetry();
        }
        for (int i = 0; i < 18; i++) {
            int j = i;
            for (int s = 0; s < 48; s++) {
                if (SymMove[s % 16][j] < i) {
                    firstMoveSym[s] |= 1 << i;
                }
                if (s % 16 == 15) {
                    j = urfMove[2][j];
                }
            }
        }
    }

    static void initFlipSym2Raw() {
        CsCubieCube c = new CsCubieCube();
        CsCubieCube d = new CsCubieCube();
        int count = 0;
        FlipR2S = new char[2048];
        for (int i = 0; i < 2048; i++) {
            if (FlipR2S[i] != 0) {
                continue;
            }
            c.setFlip(i);
            for (int s = 0; s < 16; s += 2) {
                EdgeConjugate(c, s, d);
                int idx = d.getFlip();
                if (idx == i) {
                    SymStateFlip[count] |= 1 << (s >> 1);
                }
                FlipR2S[idx] = (char) (count << 3 | s >> 1);
                if (CsSearch.USE_TWIST_FLIP_PRUN) {
                    FlipS2RF[count << 3 | s >> 1] = (char) idx;
                }
            }
            FlipS2R[count++] = (char) i;
        }
        assert count == 336;
    }

    static void initTwistSym2Raw() {
        CsCubieCube c = new CsCubieCube();
        CsCubieCube d = new CsCubieCube();
        int count = 0;
        TwistR2S = new char[2187];
        for (int i = 0; i < 2187; i++) {
            if (TwistR2S[i] != 0) {
                continue;
            }
            c.setTwist(i);
            for (int s = 0; s < 16; s += 2) {
                CornConjugate(c, s, d);
                int idx = d.getTwist();
                if (idx == i) {
                    SymStateTwist[count] |= 1 << (s >> 1);
                }
                TwistR2S[idx] = (char) (count << 3 | s >> 1);
                if (CsSearch.USE_FULL_PRUN) {
                    TwistS2RF[count << 3 | s >> 1] = (char) idx;
                }
            }
            TwistS2R[count++] = (char) i;
        }
        assert count == 324;
    }

    static byte[] Perm2Comb = new byte[2768];

    static void initPermSym2Raw() {
        CsCubieCube c = new CsCubieCube();
        CsCubieCube d = new CsCubieCube();
        int count = 0;
        EPermR2S = new char[40320];

        for (int i = 0; i < 40320; i++) {
            if (EPermR2S[i] != 0) {
                continue;
            }
            c.setEPerm(i);
            for (int s = 0; s < 16; s++) {
                EdgeConjugate(c, s, d);
                int idx = d.getEPerm();
                if (idx == i) {
                    SymStatePerm[count] |= 1 << s;
                }
                int a = d.getU4Comb();
                int b = d.getD4Comb() >> 9;
                int m = 494 - (a & 0x1ff) + (a >> 9) * 70 + b * 1680;
                MtoEPerm[m] = EPermR2S[idx] = (char) (count << 4 | s);
                if (s == 0) {
                    Perm2Comb[count] = (byte) (494 - (a & 0x1ff));
                }
            }
            EPermS2R[count++] = (char) i;
        }
        assert count == 2768;
    }

    static void initUDSliceFlipSym2Raw() {
        CsCubieCube c = new CsCubieCube();
        CsCubieCube d = new CsCubieCube();
        int[] occ = new int[2048 * 495 >> 5];
        int count = 0;
        for (int i = 0; i < 2048 * 495; i++) {
            if ((occ[i >> 5] & 1 << (i & 0x1f)) != 0) {
                continue;
            }
            c.setUDSliceFlip(i);
            for (int s = 0; s < 16; s++) {
                EdgeConjugate(c, s, d);
                int idx = d.getUDSliceFlip();
                if (idx == i) {
                    SymStateUDSliceFlip[count] |= 1 << s;
                }
                occ[idx >> 5] |= 1 << (idx & 0x1f);
                int fidx = Arrays.binarySearch(FlipS2R, (char) (idx & 0x7ff));
                if (fidx >= 0) {
                    FlipSlice2UDSliceFlip[fidx * CsCoordCube.N_SLICE + (idx >> 11)] = count << 4 | s;
                }
            }
            UDSliceFlipS2R[count++] = i;
        }
        assert count == 64430;
    }
}
